<?php

declare(strict_types=1);

use SmartDato\ArcoSpedizioni\Generators\DdtFileGenerator;

it('can create a shipment file', function () {
    $content = (new DdtFileGenerator())
        ->setField('arco_sender_client_code', '053696')
        ->setField('arco_rate_code', '')
        ->setField('invoice_grouping_code', '')
        ->setField('package_marking_code', '')
        ->setField('sender_company_name', 'BALAN')
        ->setField('sender_address', 'VIA S. AMBROGIO, 107')
        ->setField('sender_zip_code', '35010')
        ->setField('sender_city', 'TREBASELEGHE')
        ->setField('sender_province', 'PD')
        ->setField('sender_bill_invoice_number', '   B-2025-F-753')
        ->setField('sender_bill_invoice_date', '20250221')
        ->setField('sender_pre_invoice_order_delivery_number', '')
        ->setField('sender_pre_invoice_order_delivery_date', '20250221')
        ->setField('recipient_client_code', '30105335')
        ->setField('recipient_company_name', 'LA LOCANDA DEI CANTONIERI DI LA CANTONIERA SR')
        ->setField('recipient_future_uses', '')
        ->setField('recipient_address', 'VIA ARETINA, 49/D')
        ->setField('recipient_zip_code', '50066')
        ->setField('recipient_city', 'REGGELLO')
        ->setField('recipient_province', 'FI')
        ->setField('recipient_country', 'I')
        ->setField('bill_invoice_freight_type', '')

        ->setField('bill_invoice_total_packages', '6')
        ->setField('bill_invoice_total_labels', '6')
        ->setField('bill_invoice_total_pallets_to_return', '')
        ->setField('bill_invoice_total_one_way_pallets', '')
        ->setField('bill_invoice_total_weight_kg', '423')
        ->setField('bill_invoice_total_volume_m2', '12')
        ->setField('bill_invoice_total_cod_amount', '')

        ->setField('bill_invoice_cod_collection_type', '')
        ->setField('bill_invoice_total_goods_value', '')
        ->setField('delivery_mode_mandatory_delivery_date', '')
        ->setField('delivery_mode_mandatory_delivery_date_type', '')
        ->setField('delivery_mode_telephone_notice', '')
        ->setField('delivery_mode_closing_day', '')
        ->setField('delivery_mode_morning_delivery_from_hour', '')
        ->setField('delivery_mode_morning_delivery_until_hour', '')
        ->setField('delivery_mode_afternoon_delivery_from_hour', '')
        ->setField('delivery_mode_afternoon_delivery_until_hour', '')
        ->setField('delivery_mode_first_delivery_availability', '')
        ->setField('delivery_mode_second_delivery_availability', '')
        ->setField('delivery_mode_reserved_for_future_use', '')
        ->setField('delivery_mode_delivery_in_cellar', '')
        ->setField('delivery_mode_hold_flag', '')
        ->setField('delivery_mode_delivery_notes_line_1', '')
        ->setField('delivery_mode_delivery_notes_line_2', '')
        ->setField('delivery_mode_delivery_notes_line_3', '')
        ->setField('delivery_mode_delivery_notes_line_4', '')
        ->setField('delivery_mode_delivery_notes_line_5', '')
        ->setField('arco_barcode_year', '2025')
        ->setField('arco_barcode_branch_code_for_client', '999')
        ->setField('arco_barcode_shipment_number', '6001943')
        ->setField('arco_barcode_first_package_number', '1')
        ->setField('arco_barcode_routing_code', 'AR')
        ->setField('arco_barcode_routing_decoding', 'AR        /AR')
        ->setField('client_barcode_first_package_number', '2025999060019430000001AR')
        ->setField('labels_printer_name', '')
        ->setField('document_detail_row_number', '')
        ->setField('document_detail_labels_to_print', '6')
        ->setField('document_detail_item_code', '')
        ->setField('document_detail_item_description', '')
        ->setField('document_detail_item_quantity', '')
        ->setField('document_detail_package_note_line_1', '')
        ->setField('document_detail_package_note_line_2', '')
        ->setField('client_info_to_print_on_labels', '')
        ->setField('end_of_record_flag', 'E')
        ->addRecord()
        ->content();

    $result = '053696                          BALAN                              VIA S. AMBROGIO, 107          35010TREBASELEGHE                  PD   B-2025-F-75320250221                       30105335       LA LOCANDA DEI CANTONIERI DI LA CANTONIERA SR                                   VIA ARETINA, 49/D                  50066   REGGELLO                      FII   000060060000000000423001200000000 0000000000000000000                      0000000000000000                                                                                                                                                                                                                                                                2025999060019430000001AR AR        /AR       2025999060019430000001AR           000006                                                       00000                                                                                                                                                                                                                                                            E';
    expect($content)
        ->toBeString()
        ->toHaveLength(1101)
        ->toBe($result);
});
