<?php

declare(strict_types=1);

namespace SmartDato\ArcoSpedizioni\Generators;

final class DdtFileGenerator extends FileGenerator
{
    protected array $structure = [
        [
            'field' => 'arco_sender_client_code',
            'it' => 'CODICE - CLIENTE MITTENTE PER ARCO',
            'description' => '1 - arco sender client code',
            'type' => 'A',
            'length' => 6,
            'decimals' => 0,
            'start' => 1,
            'end' => 6,
            'note' => '',
        ],
        [
            'field' => 'arco_rate_code',
            'it' => 'CODICE - TARIFFA ARCO',
            'description' => '2 - arco rate code',
            'type' => 'A',
            'length' => 6,
            'decimals' => 0,
            'start' => 7,
            'end' => 12,
            'note' => '',
        ],
        [
            'field' => 'invoice_grouping_code',
            'it' => 'CODICE - RAGGRUPPAMENTO FATTURE',
            'description' => '3 - invoice grouping code',
            'type' => 'A',
            'length' => 10,
            'decimals' => 0,
            'start' => 13,
            'end' => 22,
            'note' => '',
        ],
        [
            'field' => 'package_marking_code',
            'it' => 'CODICE - MARCATURA COLLI',
            'description' => '4 - package marking code',
            'type' => 'A',
            'length' => 10,
            'decimals' => 0,
            'start' => 23,
            'end' => 32,
            'note' => '',
        ],
        [
            'field' => 'sender_company_name',
            'it' => 'MITTENTE - RAGIONE SOCIALE',
            'description' => '5 - sender company name',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 33,
            'end' => 67,
            'note' => '',
        ],
        [
            'field' => 'sender_address',
            'it' => 'MITTENTE - INDIRIZZO',
            'description' => '6 - sender address',
            'type' => 'A',
            'length' => 30,
            'decimals' => 0,
            'start' => 68,
            'end' => 97,
            'note' => '',
        ],
        [
            'field' => 'sender_zip_code',
            'it' => 'MITTENTE - CAP',
            'description' => '7 - sender zip code',
            'type' => 'A',
            'length' => 5,
            'decimals' => 0,
            'start' => 98,
            'end' => 102,
            'note' => '',
        ],
        [
            'field' => 'sender_city',
            'it' => "MITTENTE - LOCALITA'",
            'description' => '8 - sender city',
            'type' => 'A',
            'length' => 30,
            'decimals' => 0,
            'start' => 103,
            'end' => 132,
            'note' => '',
        ],
        [
            'field' => 'sender_province',
            'it' => 'MITTENTE - PROVINCIA',
            'description' => '9 - sender province',
            'type' => 'A',
            'length' => 2,
            'decimals' => 0,
            'start' => 133,
            'end' => 134,
            'note' => '',
        ],
        [
            'field' => 'sender_bill_invoice_number',
            'it' => 'MITTENTE - BOLLA / FATTURA NUMERO',
            'description' => '10 - sender bill invoice number',
            'type' => 'A',
            'length' => 15,
            'decimals' => 0,
            'start' => 135,
            'end' => 149,
            'note' => '',
        ],
        [
            'field' => 'sender_bill_invoice_date',
            'it' => 'MITTENTE - BOLLA / FATTURA DATA',
            'description' => '11 - sender bill invoice date',
            'type' => 'N',
            'length' => 8,
            'decimals' => 0,
            'start' => 150,
            'end' => 157,
            'note' => '',
        ],
        [
            'field' => 'sender_pre_invoice_order_delivery_number',
            'it' => 'MITTENTE - NUMERO PREBOLLA / ORDINE / CONSEGNA',
            'description' => '12 - sender pre invoice order delivery number',
            'type' => 'A',
            'length' => 15,
            'decimals' => 0,
            'start' => 158,
            'end' => 172,
            'note' => '',
        ],
        [
            'field' => 'sender_pre_invoice_order_delivery_date',
            'it' => 'MITTENTE - DATA PREBOLLA / ORDINE / CONSEGNA',
            'description' => '13 - sender pre invoice order delivery date',
            'type' => 'N',
            'length' => 8,
            'decimals' => 0,
            'start' => 173,
            'end' => 180,
            'note' => '',
        ],
        [
            'field' => 'recipient_client_code',
            'it' => 'DESTINATARIO - CODICE CLIENTE',
            'description' => '14 - recipient client code',
            'type' => 'A',
            'length' => 15,
            'decimals' => 0,
            'start' => 181,
            'end' => 195,
            'note' => '',
        ],
        [
            'field' => 'recipient_company_name',
            'it' => 'DESTINATARIO - RAGIONE SOCIALE',
            'description' => '15 - recipient company name',
            'type' => 'A',
            'length' => 45,
            'decimals' => 0,
            'start' => 196,
            'end' => 240,
            'note' => '',
        ],
        [
            'field' => 'recipient_future_uses',
            'it' => 'DESTINATARIO - USI FUTURI',
            'description' => '16 - recipient future uses',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 241,
            'end' => 275,
            'note' => '',
        ],
        [
            'field' => 'recipient_address',
            'it' => 'DESTINATARIO - INDIRIZZO',
            'description' => '17 - recipient address',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 276,
            'end' => 310,
            'note' => '',
        ],
        [
            'field' => 'recipient_zip_code',
            'it' => 'DESTINATARIO - CAP',
            'description' => '18 - recipient zip code',
            'type' => 'A',
            'length' => 8,
            'decimals' => 0,
            'start' => 311,
            'end' => 318,
            'note' => '',
        ],
        [
            'field' => 'recipient_city',
            'it' => "DESTINATARIO - LOCALITA'",
            'description' => '19 - recipient city',
            'type' => 'A',
            'length' => 30,
            'decimals' => 0,
            'start' => 319,
            'end' => 348,
            'note' => '',
        ],
        [
            'field' => 'recipient_province',
            'it' => 'DESTINATARIO - PROVINCIA',
            'description' => '20 - recipient province',
            'type' => 'A',
            'length' => 2,
            'decimals' => 0,
            'start' => 349,
            'end' => 350,
            'note' => '',
        ],
        [
            'field' => 'recipient_country',
            'it' => 'DESTINATARIO - NAZIONE ( I = ITALIA)',
            'description' => '21 - recipient country',
            'type' => 'A',
            'length' => 3,
            'decimals' => 0,
            'start' => 351,
            'end' => 353,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_freight_type',
            'it' => 'BOLLA / FATTURA - TIPO PORTO',
            'description' => '22 - bill invoice freight type',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 354,
            'end' => 354,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_packages',
            'it' => 'BOLLA / FATTURA - TOTALE COLLI',
            'description' => '23 - bill invoice total packages',
            'type' => 'N',
            'length' => 5,
            'decimals' => 0,
            'start' => 355,
            'end' => 359,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_labels',
            'it' => 'BOLLA / FATTURA - TOTALE ETICHETTE',
            'description' => '24 - bill invoice total labels',
            'type' => 'N',
            'length' => 3,
            'decimals' => 0,
            'start' => 360,
            'end' => 362,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_pallets_to_return',
            'it' => 'BOLLA / FATTURA - TOTALE BANCALI DA RENDERE',
            'description' => '25 - bill invoice total pallets to return',
            'type' => 'N',
            'length' => 3,
            'decimals' => 0,
            'start' => 363,
            'end' => 365,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_one_way_pallets',
            'it' => 'BOLLA / FATTURA - TOTALE BANCALI A PERDERE',
            'description' => '26 - bill invoice total one way pallets',
            'type' => 'N',
            'length' => 3,
            'decimals' => 0,
            'start' => 366,
            'end' => 368,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_weight_kg',
            'it' => 'BOLLA / FATTURA - TOTALE PESO IN KG',
            'description' => '27 - bill invoice total weight kg',
            'type' => 'N',
            'length' => 7,
            'decimals' => 1,
            'start' => 369,
            'end' => 375,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_volume_m2',
            'it' => 'BOLLE / FATTURA - TOTALE VOLUME IN MQ',
            'description' => '28 - bill invoice total volume m2',
            'type' => 'N',
            'length' => 4,
            'decimals' => 2,
            'start' => 376,
            'end' => 379,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_cod_amount',
            'it' => 'BOLLA / FATTURA - TOTALE IMPORTO CONTRASSEGNO',
            'description' => '29 - bill invoice total cod amount',
            'type' => 'N',
            'length' => 8,
            'decimals' => 2,
            'start' => 380,
            'end' => 387,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_cod_collection_type',
            'it' => 'BOLLA / FATTURA - TIPO INCASSO CONTRASSEGNO',
            'description' => '30 - bill invoice cod collection type',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 388,
            'end' => 388,
            'note' => '',
        ],
        [
            'field' => 'bill_invoice_total_goods_value',
            'it' => 'BOLLA / FATTURA - TOTALE IMPORTO VALORE MERCE',
            'description' => '31 - bill invoice total goods value',
            'type' => 'N',
            'length' => 11,
            'decimals' => 2,
            'start' => 389,
            'end' => 399,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_mandatory_delivery_date',
            'it' => "MODALITA' CONS. - DATA CONSEGNA TASSATIVA",
            'description' => '32 - delivery mode mandatory delivery date',
            'type' => 'N',
            'length' => 8,
            'decimals' => 0,
            'start' => 400,
            'end' => 407,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_mandatory_delivery_date_type',
            'it' => "MODALITA' CONS. - TIPO DATA CONSEGNA TASSATIVA",
            'description' => '33 - delivery mode mandatory delivery date type',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 408,
            'end' => 408,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_telephone_notice',
            'it' => "MODALITA' CONS. - PREAVVISO TELEFONICO",
            'description' => '34 - delivery mode telephone notice',
            'type' => 'A',
            'length' => 15,
            'decimals' => 0,
            'start' => 409,
            'end' => 423,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_closing_day',
            'it' => "MODALITA' CONS. - GIORNO CHIUSURA",
            'description' => '35 - delivery mode closing day',
            'type' => 'A',
            'length' => 6,
            'decimals' => 0,
            'start' => 424,
            'end' => 429,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_morning_delivery_from_hour',
            'it' => "MODALITA' CONS. - CONSEGNA MATTINA - DALLE ORE",
            'description' => '36 - delivery mode morning delivery from hour',
            'type' => 'N',
            'length' => 4,
            'decimals' => 0,
            'start' => 430,
            'end' => 433,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_morning_delivery_until_hour',
            'it' => "MODALITA' CONS. - CONSEGNA MATTINA - ALLE ORE",
            'description' => '37 - delivery mode morning delivery until hour',
            'type' => 'N',
            'length' => 4,
            'decimals' => 0,
            'start' => 434,
            'end' => 437,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_afternoon_delivery_from_hour',
            'it' => "MODALITA' CONS. - CONSEGNA POMERIGGIO - DALLE ORE",
            'description' => '38 - delivery mode afternoon delivery from hour',
            'type' => 'N',
            'length' => 4,
            'decimals' => 0,
            'start' => 438,
            'end' => 441,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_afternoon_delivery_until_hour',
            'it' => "MODALITA' CONS. - CONSEGNA POMERIGGIO - ALLE ORE",
            'description' => '39 - delivery mode afternoon delivery until hour',
            'type' => 'N',
            'length' => 4,
            'decimals' => 0,
            'start' => 442,
            'end' => 445,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_first_delivery_availability',
            'it' => "MODALITA' CONS. - 1A DISPOSIZIONE PER CONSEGNA",
            'description' => '40 - delivery mode first delivery availability',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 446,
            'end' => 446,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_second_delivery_availability',
            'it' => "MODALITA' CONS. - 2A DISPOSIZIONE PER CONSEGNA",
            'description' => '41 - delivery mode second delivery availability',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 447,
            'end' => 447,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_reserved_for_future_use',
            'it' => "MODALITA' CONS. - RISERVATO PER USI FUTURI",
            'description' => '42 - delivery mode reserved for future use',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 448,
            'end' => 448,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_in_cellar',
            'it' => "MODALITA' CONS. - CONSEGNA IN CANTINA",
            'description' => '43 - delivery mode delivery in cellar',
            'type' => 'A',
            'length' => 2,
            'decimals' => 0,
            'start' => 449,
            'end' => 450,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_hold_flag',
            'it' => "MODALITA' CONS. - FLAG PER FERMO DEPOSITO",
            'description' => '44 - delivery mode hold flag',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 451,
            'end' => 451,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_notes_line_1',
            'it' => "MODALITA' CONS. - NOTE PER LA CONSEGNA - 1A RIGA",
            'description' => '45 - delivery mode delivery notes line 1',
            'type' => 'A',
            'length' => 50,
            'decimals' => 0,
            'start' => 452,
            'end' => 501,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_notes_line_2',
            'it' => "MODALITA' CONS. - NOTE PER LA CONSEGNA - 2A RIGA",
            'description' => '46 - delivery mode delivery notes line 2',
            'type' => 'A',
            'length' => 50,
            'decimals' => 0,
            'start' => 502,
            'end' => 551,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_notes_line_3',
            'it' => "MODALITA' CONS. - NOTE PER LA CONSEGNA - 3A RIGA",
            'description' => '47 - delivery mode delivery notes line 3',
            'type' => 'A',
            'length' => 50,
            'decimals' => 0,
            'start' => 552,
            'end' => 601,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_notes_line_4',
            'it' => "MODALITA' CONS. - NOTE PER LA CONSEGNA - 4A RIGA",
            'description' => '48 - delivery mode delivery notes line 4',
            'type' => 'A',
            'length' => 50,
            'decimals' => 0,
            'start' => 602,
            'end' => 651,
            'note' => '',
        ],
        [
            'field' => 'delivery_mode_delivery_notes_line_5',
            'it' => "MODALITA' CONS. - NOTE PER LA CONSEGNA - 5A RIGA",
            'description' => '49 - delivery mode delivery notes line 5',
            'type' => 'A',
            'length' => 50,
            'decimals' => 0,
            'start' => 652,
            'end' => 701,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_year',
            'it' => 'BARCODE ARCO - ANNO',
            'description' => '50 - arco barcode year',
            'type' => 'N',
            'length' => 4,
            'decimals' => 0,
            'start' => 702,
            'end' => 705,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_branch_code_for_client',
            'it' => 'BARCODE ARCO - CODICE FILIALE ATTRIBUITO AL CLIENTE',
            'description' => '51 - arco barcode branch code for client',
            'type' => 'A',
            'length' => 3,
            'decimals' => 0,
            'start' => 706,
            'end' => 708,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_shipment_number',
            'it' => 'BARCODE ARCO - NUMERO SPEDIZIONE PER ARCO',
            'description' => '52 - arco barcode shipment number',
            'type' => 'N',
            'length' => 8,
            'decimals' => 0,
            'start' => 709,
            'end' => 716,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_first_package_number',
            'it' => 'BARCODE ARCO - PRIMO NUMERO COLLO (1 BYTE FISSO 0)',
            'description' => '53 - arco barcode first package number',
            'type' => 'N',
            'length' => 7,
            'decimals' => 0,
            'start' => 717,
            'end' => 723,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_routing_code',
            'it' => 'BARCODE ARCO - CODICE INSTRADAMENTO',
            'description' => '54 - arco barcode routing code',
            'type' => 'A',
            'length' => 3,
            'decimals' => 0,
            'start' => 724,
            'end' => 726,
            'note' => '',
        ],
        [
            'field' => 'arco_barcode_routing_decoding',
            'it' => 'BARCODE ARCO - DECODIFICA INSTRADAMENTO',
            'description' => '55 - arco barcode routing decoding',
            'type' => 'A',
            'length' => 20,
            'decimals' => 0,
            'start' => 727,
            'end' => 746,
            'note' => '',
        ],
        [
            'field' => 'client_barcode_first_package_number',
            'it' => 'BARCODE CLIENTE - PRIMO NUMERO COLLO',
            'description' => '56 - client barcode first package number',
            'type' => 'A',
            'length' => 25,
            'decimals' => 0,
            'start' => 747,
            'end' => 771,
            'note' => '',
        ],
        [
            'field' => 'labels_printer_name',
            'it' => 'ETICHETTE - NOME STAMPANTE PER ETICHETTE',
            'description' => '57 - labels printer name',
            'type' => 'A',
            'length' => 10,
            'decimals' => 0,
            'start' => 772,
            'end' => 781,
            'note' => '',
        ],
        [
            'field' => 'document_detail_row_number',
            'it' => 'DETTAGLIO DOCUM. - NUM RIGA NELL\'AMBITO DEL DOCUM.',
            'description' => '58 - document detail row number',
            'type' => 'N',
            'length' => 3,
            'decimals' => 0,
            'start' => 782,
            'end' => 784,
            'note' => '',
        ],
        [
            'field' => 'document_detail_labels_to_print',
            'it' => 'DETTAGLIO DOCUM. - NUMERO ETICHETTE DA STAMPARE',
            'description' => '59 - document detail labels to print',
            'type' => 'N',
            'length' => 3,
            'decimals' => 0,
            'start' => 785,
            'end' => 787,
            'note' => '',
        ],
        [
            'field' => 'document_detail_item_code',
            'it' => 'DETTAGLIO DOCUM. - CODICE ARTICOLO',
            'description' => '60 - document detail item code',
            'type' => 'A',
            'length' => 20,
            'decimals' => 0,
            'start' => 788,
            'end' => 807,
            'note' => '',
        ],
        [
            'field' => 'document_detail_item_description',
            'it' => 'DETTAGLIO DOCUM. - DESCRIZIONE ARTICOLO',
            'description' => '61 - document detail item description',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 808,
            'end' => 842,
            'note' => '',
        ],
        [
            'field' => 'document_detail_item_quantity',
            'it' => 'DETTAGLIO DOCUM. - QUANRTITA\' ARTICOLO',
            'description' => '62 - document detail item quantity',
            'type' => 'N',
            'length' => 5,
            'decimals' => 0,
            'start' => 843,
            'end' => 847,
            'note' => '',
        ],
        [
            'field' => 'document_detail_package_note_line_1',
            'it' => 'DETTAGLIO DOCUM. - 1A RIGA NOTE SEGNACOLLO',
            'description' => '63 - document detail package note line 1',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 848,
            'end' => 882,
            'note' => '',
        ],
        [
            'field' => 'document_detail_package_note_line_2',
            'it' => 'DETTAGLIO DOCUM. - 2A RIGA NOTE SEGNACOLLO',
            'description' => '64 - document detail package note line 2',
            'type' => 'A',
            'length' => 35,
            'decimals' => 0,
            'start' => 883,
            'end' => 917,
            'note' => '',
        ],
        [
            'field' => 'client_info_to_print_on_labels',
            'it' => 'INFORMAZIONI CLIENTI DA STAMPARE SU ETICHETTE',
            'description' => '65 - client info to print on labels',
            'type' => 'A',
            'length' => 182,
            'decimals' => 0,
            'start' => 918,
            'end' => 1099,
            'note' => '',
        ],
        [
            'field' => 'end_of_record_flag',
            'it' => 'FLAG FINE RECORD',
            'description' => '66 - end of record flag',
            'type' => 'A',
            'length' => 1,
            'decimals' => 0,
            'start' => 1100,
            'end' => 1100,
            'note' => '',
        ],
    ];
}
